#!/usr/bin/env bash


###########################################################################
# CONSTANTS
###########################################################################

EXIT_SUCCESS=0
EXIT_FAILURE=1
DEBUG="yes"


###########################################################################
# SOURCED FILES
###########################################################################

. oosah-trick.conf


###########################################################################
# FUNCTIONS
###########################################################################

function fun_print_usage {
	echo "usage: $0 FILE IMAGE"
	echo ""
	echo "this will embed FILE in IMAGE, so you can upload it to oosah"
	echo "and other media-only hostings."
}


function fun_args_are_fine {
	if [[ $# != 2 ]] ; then
		echo "Error: wrong number of arguments"
		false ; return
	fi

	for i in "$@" ; do
		if [[ ! -f "$i" || ! -r "$i" ]] ; then
			echo "Error: cannot read file $i"
			false ; return
		fi
	done

	true ; return
}


function fun_get_file_extension {
	echo "${1##*.}"
}


function fun_get_file_name {
	basename "${1%.*}"
}


function fun_get_image_size {
	echo "$(stat -c %s "$1")"
}


###########################################################################
# VARIABLES
###########################################################################

arg_file="$1"
arg_image="$2"

image_name="$(fun_get_file_name "$arg_image")"
image_size="$(fun_get_image_size "$arg_image")"
image_extension="$(fun_get_file_extension "$arg_image")"

if [[ $ENABLE_CRYPTO="yes" ]] ; then
	encrypted_flag="e"
else
	encrypted_flag="c"
fi

trick_file_name="${image_name}-${image_size}-${encrypted_flag}.${image_extension}"

cmd=


###########################################################################
# SCRIPT
###########################################################################

if ! fun_args_are_fine "$@" ; then
	fun_print_usage
	exit $EXIT_FAILURE
fi


# First, copy the image.
if ! cp --interactive "$arg_image" "$trick_file_name" ; then
	exit $EXIT_FAILURE
fi


# Then append the file to hide.
if [[ $ENABLE_CRYPTO = "yes" ]] ; then
	if ! $ENCRYPT_CMD $ENCRYPT_OPTIONS "$arg_file" >> "$trick_file_name" ; then
		rm $trick_file_name
		exit $EXIT_FAILURE
	fi
else
	if ! cat "$arg_file" >> "$trick_file_name" ; then
		rm $trick_file_name
		exit $EXIT_FAILURE
	fi
fi
